In [1]:
import os

import pandas as pd
from sqlalchemy import create_engine
from tqdm import tqdm
import chromadb
from chromadb.utils.embedding_functions import OpenAIEmbeddingFunction

from dotenv import load_dotenv

load_dotenv()

True

In [2]:
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD= os.getenv("POSTGRES_PASSWORD")
POSTGRES_DB= os.getenv("POSTGRES_DB")

engine = create_engine(f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@localhost:5432/{POSTGRES_DB}")

In [3]:
games = pd.DataFrame()

with engine.connect().execution_options(stream_results=True) as connection:
    query = """
    SELECT
        g.id,
        g.name,
        concat_ws(
            E'\n',
            g.summary,
            'Genres: ' || (
                SELECT string_agg(x.name, ', ' ORDER BY x.name)
                FROM game_genres gx JOIN genres x ON x.id = gx.genre_id
                WHERE gx.game_id = g.id
            ),
            'Themes: ' || (
                SELECT string_agg(x.name, ', ' ORDER BY x.name)
                FROM game_themes gx JOIN themes x ON x.id = gx.theme_id
                WHERE gx.game_id = g.id
            ),
            'Keywords: ' || (
                SELECT string_agg(x.name, ', ' ORDER BY x.name)
                FROM game_keywords gx JOIN keywords x ON x.id = gx.keyword_id
                WHERE gx.game_id = g.id
            )
        ) AS profile
    FROM games g
    ORDER BY g.total_rating_count DESC;
    """

    for chunk_df in pd.read_sql_query(query, connection, chunksize=10000):
        games = pd.concat([games, chunk_df], ignore_index=True)

In [4]:
games

,id,name,profile
0,1020,Grand Theft Auto V,Grand Theft Auto V is a vast open world game s...
1,1942,The Witcher 3: Wild Hunt,The Witcher 3: Wild Hunt is an open-world acti...
2,72,Portal 2,"Sequel to the acclaimed Portal (2007), Portal ..."
3,472,The Elder Scrolls V: Skyrim,Skyrim reimagines and revolutionizes the open-...
4,732,Grand Theft Auto: San Andreas,Returning after his mother's murder to the sem...
...,...,...,...
9995,337712,RuneScape: Dragonwilds,On RuneScape’s forgotten continent of Ashenfal...
9996,139135,Mighty Goose,Mighty Goose is a fast paced run & gun shooter...
9997,346233,Dead Reset,"Trapped in a terrifying death-loop, surgeon Co..."
9998,142986,Dadish 2,"He’s a dad, and a radish, and he’s back in his..."
9999,143772,MotoGP 21,Take your place on the starting grid and get r...

In [5]:
chroma = chromadb.HttpClient(host="localhost", port=8000)

embed = OpenAIEmbeddingFunction(api_key=os.getenv("OPENAI_API_KEY"), model_name="text-embedding-3-small")

In [6]:
def fresh_collection(name: str):
    if name in [c.name for c in chroma.list_collections()]:
        chroma.delete_collection(name)
    return chroma.create_collection(name, embedding_function=embed, metadata={"hnsw:space": "cosine"})

In [7]:
collection = fresh_collection("games")

In [8]:
BATCH = 200  # OpenAI allows ~300k tokens per request, long keyword lists make profiles big


def fill(collection, df: pd.DataFrame) -> int:
    """Embed every profile in df and add it to the collection."""
    for start in tqdm(range(0, len(df), BATCH)):
        batch = df.iloc[start:start + BATCH]
        collection.add(
            ids=batch["id"].astype(str).tolist(),
            documents=batch["profile"].tolist(),
            metadatas=[{"name": name} for name in batch["name"]]
        )
    return collection.count()


fill(collection, games)

100%|██████████| 50/50 [01:06<00:00,  1.34s/it]

10000

In [9]:
def more_like(game_id: int, n: int = 5, collection=collection):
    vector = collection.get(ids=[str(game_id)], include=["embeddings"])["embeddings"]
    result = collection.query(query_embeddings=vector, n_results=n + 1)  # +1: the game itself comes first
    return [(m["name"], round(d, 3)) for m, d in zip(result["metadatas"][0][1:], result["distances"][0][1:])]

def recommend(query: str, n: int = 5, collection=collection):
    result = collection.query(query_texts=[query], n_results=n)
    return [(m["name"], round(d, 3)) for m, d in zip(result["metadatas"][0], result["distances"][0])]

In [10]:
more_like(1942, 10)  # The Witcher 3

[('The Witcher 2: Assassins of Kings', 0.205),
 ('The Witcher', 0.217),
 ('The Witcher: Adventure Game', 0.239),
 ('Middle-earth: Shadow of Mordor', 0.347),
 ('The Witcher: Monster Slayer', 0.348),
 ('The Elder Scrolls V: Skyrim', 0.349),
 ('Dishonored', 0.358),
 ('Fallout 3', 0.359),
 ('Nightingale', 0.366),
 ('Gwent: The Witcher Card Game', 0.367)]

In [11]:
recommend("cozy farming game with co-op")

[('Farm Together', 0.35),
 ('Farming Simulator 22', 0.368),
 ('Harvest Moon: Friends of Mineral Town', 0.381),
 ("My Grandfather's Farm", 0.429),
 ('Sunflower Land', 0.437)]

In [12]:
collection_no_keywords = fresh_collection("games_no_keywords")

In [13]:
games_no_keywords = pd.DataFrame()

with engine.connect().execution_options(stream_results=True) as connection:
    query = """
    SELECT
        g.id,
        g.name,
        concat_ws(
            E'\n',
            g.summary,
            'Genres: ' || (
                SELECT string_agg(x.name, ', ' ORDER BY x.name)
                FROM game_genres gx JOIN genres x ON x.id = gx.genre_id
                WHERE gx.game_id = g.id
            ),
            'Themes: ' || (
                SELECT string_agg(x.name, ', ' ORDER BY x.name)
                FROM game_themes gx JOIN themes x ON x.id = gx.theme_id
                WHERE gx.game_id = g.id
            )
        ) AS profile
    FROM games g
    ORDER BY g.total_rating_count DESC;
    """

    for chunk_df in pd.read_sql_query(query, connection, chunksize=10000):
        games_no_keywords = pd.concat([games_no_keywords, chunk_df], ignore_index=True)

In [14]:
games_no_keywords

,id,name,profile
0,1020,Grand Theft Auto V,Grand Theft Auto V is a vast open world game s...
1,1942,The Witcher 3: Wild Hunt,The Witcher 3: Wild Hunt is an open-world acti...
2,72,Portal 2,"Sequel to the acclaimed Portal (2007), Portal ..."
3,472,The Elder Scrolls V: Skyrim,Skyrim reimagines and revolutionizes the open-...
4,732,Grand Theft Auto: San Andreas,Returning after his mother's murder to the sem...
...,...,...,...
9995,337712,RuneScape: Dragonwilds,On RuneScape’s forgotten continent of Ashenfal...
9996,139135,Mighty Goose,Mighty Goose is a fast paced run & gun shooter...
9997,346233,Dead Reset,"Trapped in a terrifying death-loop, surgeon Co..."
9998,142986,Dadish 2,"He’s a dad, and a radish, and he’s back in his..."
9999,143772,MotoGP 21,Take your place on the starting grid and get r...

In [15]:
fill(collection_no_keywords, games_no_keywords)

100%|██████████| 50/50 [01:21<00:00,  1.62s/it]

10000

In [16]:
def compare(results_with: list, results_without: list) -> pd.DataFrame:
    """Show the same Recommendation from both collections side by side."""
    return pd.DataFrame({"with keywords": results_with, "without keywords": results_without})


compare(more_like(1942, 10), more_like(1942, 10, collection=collection_no_keywords))  # The Witcher 3

,with keywords,without keywords
0,"(The Witcher 2: Assassins of Kings, 0.205)","(The Witcher 2: Assassins of Kings, 0.257)"
1,"(The Witcher, 0.217)","(The Witcher: Adventure Game, 0.285)"
2,"(The Witcher: Adventure Game, 0.239)","(The Witcher, 0.308)"
3,"(Middle-earth: Shadow of Mordor, 0.347)","(The Witcher: Monster Slayer, 0.374)"
4,"(The Witcher: Monster Slayer, 0.348)","(The Witcher Battle Arena, 0.4)"
5,"(The Elder Scrolls V: Skyrim, 0.349)","(Gwent: The Witcher Card Game, 0.416)"
6,"(Dishonored, 0.358)","(Gothic 3, 0.445)"
7,"(Fallout 3, 0.359)","(Wytchwood, 0.449)"
8,"(Nightingale, 0.366)","(Wolcen: Lords of Mayhem, 0.458)"
9,"(Gwent: The Witcher Card Game, 0.367)","(Dragon Age: Inquisition, 0.462)"

In [17]:
user_query = "Rocket League but with more cars and more explosions"
compare(recommend(user_query, 10), recommend(user_query, 10, collection=collection_no_keywords))

,with keywords,without keywords
0,"(Rocket League, 0.296)","(Rocket League, 0.287)"
1,"(Rocket League Sideswipe, 0.343)","(Rocket League Sideswipe, 0.343)"
2,(Supersonic Acrobatic Rocket-Powered Battle-Ca...,(Supersonic Acrobatic Rocket-Powered Battle-Ca...
3,"(Dirt Showdown, 0.449)","(Wreckfest, 0.462)"
4,"(Pole Position II, 0.46)","(Hot Wheels Unleashed 2: Turbocharged, 0.463)"
5,"(Wreckfest, 0.46)","(Crashday, 0.467)"
6,"(Danger Zone, 0.461)","(Gear.Club Unlimited, 0.469)"
7,"(Hot Wheels Unleashed 2: Turbocharged, 0.463)","(Danger Zone, 0.474)"
8,"(Gear.Club Unlimited, 0.469)","(FlatOut 2, 0.477)"
9,"(Crashday, 0.471)","(Micro Machines V4, 0.481)"